#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_DDWLeg

#include "Basic.hpp"

#include "ABP_DDWLeg_classes.hpp"
#include "ABP_DDWLeg_parameters.hpp"


SDK_NAMESPACE_START

// Function ABP_DDWLeg.ABP_DDWLeg_C.ExecuteUbergraph_ABP_DDWLeg
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_DDWLeg_C::ExecuteUbergraph_ABP_DDWLeg(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_DDWLeg_C", "ExecuteUbergraph_ABP_DDWLeg");

	Params::ABP_DDWLeg_C_ExecuteUbergraph_ABP_DDWLeg Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
