#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_AJBInGameStand_DDW

#include "Basic.hpp"

#include "ABP_AJBInGameStand_DDW_classes.hpp"
#include "ABP_AJBInGameStand_DDW_parameters.hpp"


SDK_NAMESPACE_START

// Function ABP_AJBInGameStand_DDW.ABP_AJBInGameStand_DDW_C.ExecuteUbergraph_ABP_AJBInGameStand_DDW
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_AJBInGameStand_DDW_C::ExecuteUbergraph_ABP_AJBInGameStand_DDW(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_AJBInGameStand_DDW_C", "ExecuteUbergraph_ABP_AJBInGameStand_DDW");

	Params::ABP_AJBInGameStand_DDW_C_ExecuteUbergraph_ABP_AJBInGameStand_DDW Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_AJBInGameStand_DDW.ABP_AJBInGameStand_DDW_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_AJBInGameStand_DDW_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_AJBInGameStand_DDW_C", "BlueprintUpdateAnimation");

	Params::ABP_AJBInGameStand_DDW_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_AJBInGameStand_DDW.ABP_AJBInGameStand_DDW_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AJBInGameStand_DDW_AnimGraphNode_TransitionResult_6C24AD694AD35B6E36D616A34FC242E3
// (BlueprintEvent)

void UABP_AJBInGameStand_DDW_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AJBInGameStand_DDW_AnimGraphNode_TransitionResult_6C24AD694AD35B6E36D616A34FC242E3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_AJBInGameStand_DDW_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AJBInGameStand_DDW_AnimGraphNode_TransitionResult_6C24AD694AD35B6E36D616A34FC242E3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_AJBInGameStand_DDW.ABP_AJBInGameStand_DDW_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AJBInGameStand_DDW_AnimGraphNode_TransitionResult_2925122047B47CF9D9D5A6BE5BD56555
// (BlueprintEvent)

void UABP_AJBInGameStand_DDW_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AJBInGameStand_DDW_AnimGraphNode_TransitionResult_2925122047B47CF9D9D5A6BE5BD56555()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_AJBInGameStand_DDW_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AJBInGameStand_DDW_AnimGraphNode_TransitionResult_2925122047B47CF9D9D5A6BE5BD56555");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_AJBInGameStand_DDW.ABP_AJBInGameStand_DDW_C.CanOwnerMove
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   bCanMove                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UABP_AJBInGameStand_DDW_C::CanOwnerMove(bool* bCanMove)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_AJBInGameStand_DDW_C", "CanOwnerMove");

	Params::ABP_AJBInGameStand_DDW_C_CanOwnerMove Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bCanMove != nullptr)
		*bCanMove = Parms.bCanMove;
}


SDK_NAMESPACE_END
