#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_AJBInGameSub_MovementDIO

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ABP_AJBIngameSub_Movement_classes.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass ABP_AJBInGameSub_MovementDIO.ABP_AJBInGameSub_MovementDIO_C
// 0x0008 (0x2F18 - 0x2F10)
class UABP_AJBInGameSub_MovementDIO_C final : public UABP_AJBIngameSub_Movement_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_ABP_AJBInGameSub_MovementDIO_C;     // 0x2F10(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_ABP_AJBInGameSub_MovementDIO(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_AJBInGameSub_MovementDIO_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_AJBInGameSub_MovementDIO_C")
	}
	static class UABP_AJBInGameSub_MovementDIO_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_AJBInGameSub_MovementDIO_C>();
	}
};
DUMPER7_ASSERTS_UABP_AJBInGameSub_MovementDIO_C;

SDK_NAMESPACE_END
