#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BI_DamageImpulseInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BI_DamageImpulseInterface.BI_DamageImpulseInterface_C
// 0x0000 (0x0000 - 0x0000)
class IBI_DamageImpulseInterface_C final
{
public:
	void GetTargetLocation(struct FVector* Location);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BI_DamageImpulseInterface_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BI_DamageImpulseInterface_C")
	}
	static class IBI_DamageImpulseInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBI_DamageImpulseInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBI_DamageImpulseInterface_C;

SDK_NAMESPACE_END
