#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BI_MovementSkill

#include "Basic.hpp"

#include "BI_MovementSkill_classes.hpp"
#include "BI_MovementSkill_parameters.hpp"


SDK_NAMESPACE_START

// Function BI_MovementSkill.BI_MovementSkill_C.ChangeMovementDistanceScale
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBI_MovementSkill_C::ChangeMovementDistanceScale(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BI_MovementSkill_C", "ChangeMovementDistanceScale");

	Params::BI_MovementSkill_C_ChangeMovementDistanceScale Parms{};

	Parms.Value = Value;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BI_MovementSkill.BI_MovementSkill_C.ChangeStandMovementDistanceScale
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBI_MovementSkill_C::ChangeStandMovementDistanceScale(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BI_MovementSkill_C", "ChangeStandMovementDistanceScale");

	Params::BI_MovementSkill_C_ChangeStandMovementDistanceScale Parms{};

	Parms.Value = Value;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BI_MovementSkill.BI_MovementSkill_C.ChangeStandLaunchVelocityScale
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBI_MovementSkill_C::ChangeStandLaunchVelocityScale(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BI_MovementSkill_C", "ChangeStandLaunchVelocityScale");

	Params::BI_MovementSkill_C_ChangeStandLaunchVelocityScale Parms{};

	Parms.Value = Value;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BI_MovementSkill.BI_MovementSkill_C.ChangeCharacterMoveSpeedByStand
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBI_MovementSkill_C::ChangeCharacterMoveSpeedByStand(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BI_MovementSkill_C", "ChangeCharacterMoveSpeedByStand");

	Params::BI_MovementSkill_C_ChangeCharacterMoveSpeedByStand Parms{};

	Parms.Value = Value;

	AsUObject()->ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
