#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBInGameAIDirector

#include "Basic.hpp"

#include "BP_AJBInGameAIDirector_classes.hpp"
#include "BP_AJBInGameAIDirector_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.ExecuteUbergraph_BP_AJBInGameAIDirector
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::ExecuteUbergraph_BP_AJBInGameAIDirector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "ExecuteUbergraph_BP_AJBInGameAIDirector");

	Params::BP_AJBInGameAIDirector_C_ExecuteUbergraph_BP_AJBInGameAIDirector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.AddSpecialNPC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              CharacterTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FTransform&                Transform                                              (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// uint8                                   AILevel_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              SpecialTag                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class AActor*                           ContextActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SerialNumber                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::AddSpecialNPC(const struct FGameplayTag& CharacterTag, const struct FTransform& Transform, uint8 AILevel_0, const struct FGameplayTag& SpecialTag, class AActor* ContextActor, int32 SerialNumber)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "AddSpecialNPC");

	Params::BP_AJBInGameAIDirector_C_AddSpecialNPC Parms{};

	Parms.CharacterTag = std::move(CharacterTag);
	Parms.Transform = std::move(Transform);
	Parms.AILevel_0 = AILevel_0;
	Parms.SpecialTag = std::move(SpecialTag);
	Parms.ContextActor = ContextActor;
	Parms.SerialNumber = SerialNumber;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.StartSHABehavior
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AJBInGameAIController_C*      AIController                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::StartSHABehavior(class ABP_AJBInGameAIController_C* AIController, float Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "StartSHABehavior");

	Params::BP_AJBInGameAIDirector_C_StartSHABehavior Parms{};

	Parms.AIController = AIController;
	Parms.Delay = Delay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.OnStartLastSurvivorScene
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBInGameAIDirector_C::OnStartLastSurvivorScene()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "OnStartLastSurvivorScene");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.SetupRelationships
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBInGameAIDirector_C::SetupRelationships()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "SetupRelationships");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugRunNPC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AJBInGameAIController_C*      AI_Controller                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UBehaviorTree*                    BehaviorTreeAsset                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UBehaviorTree*                    SubTreeAsset                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugRunNPC(class ABP_AJBInGameAIController_C* AI_Controller, class UBehaviorTree* BehaviorTreeAsset, class UBehaviorTree* SubTreeAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugRunNPC");

	Params::BP_AJBInGameAIDirector_C_DebugRunNPC Parms{};

	Parms.AI_Controller = AI_Controller;
	Parms.BehaviorTreeAsset = BehaviorTreeAsset;
	Parms.SubTreeAsset = SubTreeAsset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugStartBehavior
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AJBInGameAIController_C*      AI_Controller                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UBehaviorTree*                    BehaviorTreeAsset                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UBehaviorTree*                    SubTreeAsset                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugStartBehavior(class ABP_AJBInGameAIController_C* AI_Controller, class UBehaviorTree* BehaviorTreeAsset, class UBehaviorTree* SubTreeAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugStartBehavior");

	Params::BP_AJBInGameAIDirector_C_DebugStartBehavior Parms{};

	Parms.AI_Controller = AI_Controller;
	Parms.BehaviorTreeAsset = BehaviorTreeAsset;
	Parms.SubTreeAsset = SubTreeAsset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.AddPlayerCharacterInfo
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AJBInGameCharacter_C*         InGameCharacter                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::AddPlayerCharacterInfo(class ABP_AJBInGameCharacter_C* InGameCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "AddPlayerCharacterInfo");

	Params::BP_AJBInGameAIDirector_C_AddPlayerCharacterInfo Parms{};

	Parms.InGameCharacter = InGameCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.SetupEnvironment
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBInGameAIDirector_C::SetupEnvironment()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "SetupEnvironment");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.StartDefaultBehavior
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AJBInGameAIController_C*      AI_Controller                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::StartDefaultBehavior(class ABP_AJBInGameAIController_C* AI_Controller, float Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "StartDefaultBehavior");

	Params::BP_AJBInGameAIDirector_C_StartDefaultBehavior Parms{};

	Parms.AI_Controller = AI_Controller;
	Parms.Delay = Delay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.AddBattleNPCFromDebug
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              CharacterTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FTransform&                Transform                                              (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// uint8                                   AI_Level                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::AddBattleNPCFromDebug(const struct FGameplayTag& CharacterTag, const struct FTransform& Transform, uint8 AI_Level)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "AddBattleNPCFromDebug");

	Params::BP_AJBInGameAIDirector_C_AddBattleNPCFromDebug Parms{};

	Parms.CharacterTag = std::move(CharacterTag);
	Parms.Transform = std::move(Transform);
	Parms.AI_Level = AI_Level;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.RunNPC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AJBInGameAIController_C*      AIController                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              SpecialTag                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::RunNPC(class ABP_AJBInGameAIController_C* AIController, float Delay, const struct FGameplayTag& SpecialTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "RunNPC");

	Params::BP_AJBInGameAIDirector_C_RunNPC Parms{};

	Parms.AIController = AIController;
	Parms.Delay = Delay;
	Parms.SpecialTag = std::move(SpecialTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.RunAllNPCs
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBInGameAIDirector_C::RunAllNPCs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "RunAllNPCs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.StartGameplay
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBInGameAIDirector_C::StartGameplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "StartGameplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.AddBattleNPC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              CharacterTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FTransform&                Transform                                              (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// uint8                                   AILevel_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::AddBattleNPC(const struct FGameplayTag& CharacterTag, const struct FTransform& Transform, uint8 AILevel_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "AddBattleNPC");

	Params::BP_AJBInGameAIDirector_C_AddBattleNPC Parms{};

	Parms.CharacterTag = std::move(CharacterTag);
	Parms.Transform = std::move(Transform);
	Parms.AILevel_0 = AILevel_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "ReceiveTick");

	Params::BP_AJBInGameAIDirector_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_AJBInGameAIDirector_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugGetNavigationPathLocations
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerControler                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugGetNavigationPathLocations(class APlayerController* PlayerControler, const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugGetNavigationPathLocations");

	Params::BP_AJBInGameAIDirector_C_DebugGetNavigationPathLocations Parms{};

	Parms.PlayerControler = PlayerControler;
	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugRequestEventReplaySHA
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                ClientController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugRequestEventReplaySHA(class APlayerController* ClientController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugRequestEventReplaySHA");

	Params::BP_AJBInGameAIDirector_C_DebugRequestEventReplaySHA Parms{};

	Parms.ClientController = ClientController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugSetupEventReplayForSpecialNPC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AJBInGameCharacter_C*         Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              SpecialTag                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugSetupEventReplayForSpecialNPC(class ABP_AJBInGameCharacter_C* Character, const struct FGameplayTag& SpecialTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugSetupEventReplayForSpecialNPC");

	Params::BP_AJBInGameAIDirector_C_DebugSetupEventReplayForSpecialNPC Parms{};

	Parms.Character = Character;
	Parms.SpecialTag = std::move(SpecialTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugSendNavMeshPointAround
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugSendNavMeshPointAround(class APlayerController* PlayerController, const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugSendNavMeshPointAround");

	Params::BP_AJBInGameAIDirector_C_DebugSendNavMeshPointAround Parms{};

	Parms.PlayerController = PlayerController;
	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugRequestByGameplayTags
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTagContainer&     Tags                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FVector&                   VectorIn                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugRequestByGameplayTags(class APlayerController* PlayerController, const struct FGameplayTagContainer& Tags, const struct FVector& VectorIn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugRequestByGameplayTags");

	Params::BP_AJBInGameAIDirector_C_DebugRequestByGameplayTags Parms{};

	Parms.PlayerController = PlayerController;
	Parms.Tags = std::move(Tags);
	Parms.VectorIn = std::move(VectorIn);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugRequestAddNPCFromDebugArgs
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FRotator&                  Rotation                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor)
// const struct FGameplayTagContainer&     AddInfoTags                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   AILevel_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugRequestAddNPCFromDebugArgs(const struct FVector& Location, const struct FRotator& Rotation, const struct FGameplayTagContainer& AddInfoTags, int32 AILevel_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugRequestAddNPCFromDebugArgs");

	Params::BP_AJBInGameAIDirector_C_DebugRequestAddNPCFromDebugArgs Parms{};

	Parms.Location = std::move(Location);
	Parms.Rotation = std::move(Rotation);
	Parms.AddInfoTags = std::move(AddInfoTags);
	Parms.AILevel_0 = AILevel_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugOnBeginPlay
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBInGameAIDirector_C::DebugOnBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugOnBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.OnFinishedDelayForStartBehavior
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AJBInGameAIController_C*      AI_Controller                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_AJBDebugAIStartPoint_C*       DebugAIStartPoint                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::OnFinishedDelayForStartBehavior(class ABP_AJBInGameAIController_C* AI_Controller, class ABP_AJBDebugAIStartPoint_C* DebugAIStartPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "OnFinishedDelayForStartBehavior");

	Params::BP_AJBInGameAIDirector_C_OnFinishedDelayForStartBehavior Parms{};

	Parms.AI_Controller = AI_Controller;
	Parms.DebugAIStartPoint = DebugAIStartPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugRequestAddNPCFromDebugActor
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugRequestAddNPCFromDebugActor(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugRequestAddNPCFromDebugActor");

	Params::BP_AJBInGameAIDirector_C_DebugRequestAddNPCFromDebugActor Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugRequestNPCAllLog
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NPCId                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugRequestNPCAllLog(class APlayerController* PlayerController, int32 NPCId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugRequestNPCAllLog");

	Params::BP_AJBInGameAIDirector_C_DebugRequestNPCAllLog Parms{};

	Parms.PlayerController = PlayerController;
	Parms.NPCId = NPCId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugChangeDefaultAILevel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   AI_Level_As_Default                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugChangeDefaultAILevel(int32 AI_Level_As_Default)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugChangeDefaultAILevel");

	Params::BP_AJBInGameAIDirector_C_DebugChangeDefaultAILevel Parms{};

	Parms.AI_Level_As_Default = AI_Level_As_Default;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugRequestHideDebugInfo
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugRequestHideDebugInfo(class APlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugRequestHideDebugInfo");

	Params::BP_AJBInGameAIDirector_C_DebugRequestHideDebugInfo Parms{};

	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugRequestShowDebugInfo
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugRequestShowDebugInfo(class APlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugRequestShowDebugInfo");

	Params::BP_AJBInGameAIDirector_C_DebugRequestShowDebugInfo Parms{};

	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugRequestRestartBehavior
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   DebugMenuIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugRequestRestartBehavior(int32 DebugMenuIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugRequestRestartBehavior");

	Params::BP_AJBInGameAIDirector_C_DebugRequestRestartBehavior Parms{};

	Parms.DebugMenuIndex = DebugMenuIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugShowSingleNPCDebugInfo
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_AJBAIMessenger_C*             AI_Messenger                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_AJBInGameAIController_C*      AI_Controller                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugShowSingleNPCDebugInfo(class UBP_AJBAIMessenger_C* AI_Messenger, class ABP_AJBInGameAIController_C* AI_Controller, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugShowSingleNPCDebugInfo");

	Params::BP_AJBInGameAIDirector_C_DebugShowSingleNPCDebugInfo Parms{};

	Parms.AI_Messenger = AI_Messenger;
	Parms.AI_Controller = AI_Controller;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.OnSpawnForDebugShowNPCStatus
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AJBInGameAIController_C*      AI_Controller                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::OnSpawnForDebugShowNPCStatus(class ABP_AJBInGameAIController_C* AI_Controller, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "OnSpawnForDebugShowNPCStatus");

	Params::BP_AJBInGameAIDirector_C_OnSpawnForDebugShowNPCStatus Parms{};

	Parms.AI_Controller = AI_Controller;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.OnDeadForDebugShowNPCStatus
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AAIController*                    AIController                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              DamageType                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::OnDeadForDebugShowNPCStatus(class AAIController* AIController, const struct FGameplayTag& DamageType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "OnDeadForDebugShowNPCStatus");

	Params::BP_AJBInGameAIDirector_C_OnDeadForDebugShowNPCStatus Parms{};

	Parms.AIController = AIController;
	Parms.DamageType = std::move(DamageType);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugUpdateSingleNPCStatus
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_AJBAIMessenger_C*             AIMessenger                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::DebugUpdateSingleNPCStatus(class UBP_AJBAIMessenger_C* AIMessenger, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugUpdateSingleNPCStatus");

	Params::BP_AJBInGameAIDirector_C_DebugUpdateSingleNPCStatus Parms{};

	Parms.AIMessenger = AIMessenger;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.DebugUpdateNPCsStatus
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBInGameAIDirector_C::DebugUpdateNPCsStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "DebugUpdateNPCsStatus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.GetImplementedCharacterClasses
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class UClass*>*                  ImplementedCharacterClasses                            (Parm, OutParm, ZeroConstructor)

void UBP_AJBInGameAIDirector_C::GetImplementedCharacterClasses(TArray<class UClass*>* ImplementedCharacterClasses)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "GetImplementedCharacterClasses");

	Params::BP_AJBInGameAIDirector_C_GetImplementedCharacterClasses Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ImplementedCharacterClasses != nullptr)
		*ImplementedCharacterClasses = std::move(Parms.ImplementedCharacterClasses);
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.FindNearestStartPoint
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class AActor* UBP_AJBInGameAIDirector_C::FindNearestStartPoint(const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "FindNearestStartPoint");

	Params::BP_AJBInGameAIDirector_C_FindNearestStartPoint Parms{};

	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.SpawnBattleNPCCharacter
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FTransform&                SpawnTransform                                         (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// uint8                                   SpawnAILevel                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              CharacterTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Owner                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bRunNPC                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class ABP_AJBInGameAIController_C**     AIController                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_AJBInGameCharacter_C**        NPCCharacter                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::SpawnBattleNPCCharacter(const struct FTransform& SpawnTransform, uint8 SpawnAILevel, const struct FGameplayTag& CharacterTag, class AActor* Owner, bool bRunNPC, class ABP_AJBInGameAIController_C** AIController, class ABP_AJBInGameCharacter_C** NPCCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "SpawnBattleNPCCharacter");

	Params::BP_AJBInGameAIDirector_C_SpawnBattleNPCCharacter Parms{};

	Parms.SpawnTransform = std::move(SpawnTransform);
	Parms.SpawnAILevel = SpawnAILevel;
	Parms.CharacterTag = std::move(CharacterTag);
	Parms.Owner = Owner;
	Parms.bRunNPC = bRunNPC;

	UObject::ProcessEvent(Func, &Parms);

	if (AIController != nullptr)
		*AIController = Parms.AIController;

	if (NPCCharacter != nullptr)
		*NPCCharacter = Parms.NPCCharacter;
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.GetCountOfAIControllers
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_AJBInGameAIDirector_C::GetCountOfAIControllers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "GetCountOfAIControllers");

	Params::BP_AJBInGameAIDirector_C_GetCountOfAIControllers Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.GetNPCIdFromPawn
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            Pawn                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_AJBInGameAIDirector_C::GetNPCIdFromPawn(class APawn* Pawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "GetNPCIdFromPawn");

	Params::BP_AJBInGameAIDirector_C_GetNPCIdFromPawn Parms{};

	Parms.Pawn = Pawn;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_AJBInGameAIDirector.BP_AJBInGameAIDirector_C.RemoveImaginaryCache
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class APawn*&                     OwningCharacter                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBInGameAIDirector_C::RemoveImaginaryCache(const class APawn*& OwningCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBInGameAIDirector_C", "RemoveImaginaryCache");

	Params::BP_AJBInGameAIDirector_C_RemoveImaginaryCache Parms{};

	Parms.OwningCharacter = OwningCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
