#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBTheWorldSkill

#include "Basic.hpp"

#include "BP_AJBTheWorldSkill_classes.hpp"
#include "BP_AJBTheWorldSkill_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.ExecuteUbergraph_BP_AJBTheWorldSkill
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBTheWorldSkill_C::ExecuteUbergraph_BP_AJBTheWorldSkill(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "ExecuteUbergraph_BP_AJBTheWorldSkill");

	Params::BP_AJBTheWorldSkill_C_ExecuteUbergraph_BP_AJBTheWorldSkill Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.EndState
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBTheWorldSkill_C::EndState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "EndState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.StateBegin_Action
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBTheWorldSkill_C::StateBegin_Action()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "StateBegin_Action");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.StateTick_Action
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBTheWorldSkill_C::StateTick_Action()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "StateTick_Action");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.StateTick
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBTheWorldSkill_C::StateTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "StateTick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.AddStopTime
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Seconds                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBTheWorldSkill_C::AddStopTime(float Seconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "AddStopTime");

	Params::BP_AJBTheWorldSkill_C_AddStopTime Parms{};

	Parms.Seconds = Seconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.TryGetValidAffecter
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ABP_AJBTheWorldAffecter_C**       Affecter                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBTheWorldSkill_C::TryGetValidAffecter(class ABP_AJBTheWorldAffecter_C** Affecter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "TryGetValidAffecter");

	Params::BP_AJBTheWorldSkill_C_TryGetValidAffecter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Affecter != nullptr)
		*Affecter = Parms.Affecter;
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.SubStopTime
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Seconds                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBTheWorldSkill_C::SubStopTime(float Seconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "SubStopTime");

	Params::BP_AJBTheWorldSkill_C_SubStopTime Parms{};

	Parms.Seconds = Seconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_AJBTheWorldSkill_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.OnCancel
// (Event, Public, BlueprintEvent)

void UBP_AJBTheWorldSkill_C::OnCancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "OnCancel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.OnActive
// (Event, Public, BlueprintEvent)

void UBP_AJBTheWorldSkill_C::OnActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "OnActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBTheWorldSkill_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "ReceiveTick");

	Params::BP_AJBTheWorldSkill_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.OnInactive
// (Event, Public, BlueprintEvent)

void UBP_AJBTheWorldSkill_C::OnInactive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "OnInactive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.OnRelatedCharacterBecomeLastSurvivor
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AJBTheWorldSkill_C::OnRelatedCharacterBecomeLastSurvivor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "OnRelatedCharacterBecomeLastSurvivor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.TimeExtension_Server
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBTheWorldSkill_C::TimeExtension_Server(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "TimeExtension_Server");

	Params::BP_AJBTheWorldSkill_C_TimeExtension_Server Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBTheWorldSkill.BP_AJBTheWorldSkill_C.TimeRewind_Server
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBTheWorldSkill_C::TimeRewind_Server(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBTheWorldSkill_C", "TimeRewind_Server");

	Params::BP_AJBTheWorldSkill_C_TimeRewind_Server Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
