#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBC29MeleeFlinch

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_AJBFlinchBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AJBC29MeleeFlinch.BP_AJBC29MeleeFlinch_C
// 0x0008 (0x0238 - 0x0230)
class UBP_AJBC29MeleeFlinch_C final : public UBP_AJBFlinchBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_AJBC29MeleeFlinch_C;             // 0x0230(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_AJBC29MeleeFlinch(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AJBC29MeleeFlinch_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AJBC29MeleeFlinch_C")
	}
	static class UBP_AJBC29MeleeFlinch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AJBC29MeleeFlinch_C>();
	}
};
DUMPER7_ASSERTS_UBP_AJBC29MeleeFlinch_C;

SDK_NAMESPACE_END
