#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBBitesTheDustSkill

#include "Basic.hpp"

#include "BP_AJBBitesTheDustSkill_classes.hpp"
#include "BP_AJBBitesTheDustSkill_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AJBBitesTheDustSkill.BP_AJBBitesTheDustSkill_C.ExecuteUbergraph_BP_AJBBitesTheDustSkill
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBBitesTheDustSkill_C::ExecuteUbergraph_BP_AJBBitesTheDustSkill(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBBitesTheDustSkill_C", "ExecuteUbergraph_BP_AJBBitesTheDustSkill");

	Params::BP_AJBBitesTheDustSkill_C_ExecuteUbergraph_BP_AJBBitesTheDustSkill Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBBitesTheDustSkill.BP_AJBBitesTheDustSkill_C.ShouldRemainHP
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bShouldRemain                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_AJBBitesTheDustSkill_C::ShouldRemainHP(bool* bShouldRemain)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBBitesTheDustSkill_C", "ShouldRemainHP");

	Params::BP_AJBBitesTheDustSkill_C_ShouldRemainHP Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bShouldRemain != nullptr)
		*bShouldRemain = Parms.bShouldRemain;
}


// Function BP_AJBBitesTheDustSkill.BP_AJBBitesTheDustSkill_C.GetSkillAffecterServer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           AffecterClass                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_AJBSkillAffecterBase_C**      SkillAffecter_0                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBBitesTheDustSkill_C::GetSkillAffecterServer(class UClass* AffecterClass, class ABP_AJBSkillAffecterBase_C** SkillAffecter_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBBitesTheDustSkill_C", "GetSkillAffecterServer");

	Params::BP_AJBBitesTheDustSkill_C_GetSkillAffecterServer Parms{};

	Parms.AffecterClass = AffecterClass;

	UObject::ProcessEvent(Func, &Parms);

	if (SkillAffecter_0 != nullptr)
		*SkillAffecter_0 = Parms.SkillAffecter_0;
}


// Function BP_AJBBitesTheDustSkill.BP_AJBBitesTheDustSkill_C.ActiveBitesTheDust
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AJBBitesTheDustSkill_C::ActiveBitesTheDust()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBBitesTheDustSkill_C", "ActiveBitesTheDust");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBBitesTheDustSkill.BP_AJBBitesTheDustSkill_C.SetSkillAffecterSettings
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AJBBitesTheDustSkill_C::SetSkillAffecterSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBBitesTheDustSkill_C", "SetSkillAffecterSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBBitesTheDustSkill.BP_AJBBitesTheDustSkill_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_AJBBitesTheDustSkill_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBBitesTheDustSkill_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBBitesTheDustSkill.BP_AJBBitesTheDustSkill_C.OnRelatedCharacterBecomeLastSurvivor
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AJBBitesTheDustSkill_C::OnRelatedCharacterBecomeLastSurvivor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBBitesTheDustSkill_C", "OnRelatedCharacterBecomeLastSurvivor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBBitesTheDustSkill.BP_AJBBitesTheDustSkill_C.PowerUpServer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBBitesTheDustSkill_C::PowerUpServer(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBBitesTheDustSkill_C", "PowerUpServer");

	Params::BP_AJBBitesTheDustSkill_C_PowerUpServer Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBBitesTheDustSkill.BP_AJBBitesTheDustSkill_C.PowerDown_Server
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBBitesTheDustSkill_C::PowerDown_Server(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBBitesTheDustSkill_C", "PowerDown_Server");

	Params::BP_AJBBitesTheDustSkill_C_PowerDown_Server Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
