#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBMultipleLocationsActorBase

#include "Basic.hpp"

#include "BP_AJBMultipleLocationsActorBase_classes.hpp"
#include "BP_AJBMultipleLocationsActorBase_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AJBMultipleLocationsActorBase.BP_AJBMultipleLocationsActorBase_C.ExecuteUbergraph_BP_AJBMultipleLocationsActorBase
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBMultipleLocationsActorBase_C::ExecuteUbergraph_BP_AJBMultipleLocationsActorBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBMultipleLocationsActorBase_C", "ExecuteUbergraph_BP_AJBMultipleLocationsActorBase");

	Params::BP_AJBMultipleLocationsActorBase_C_ExecuteUbergraph_BP_AJBMultipleLocationsActorBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBMultipleLocationsActorBase.BP_AJBMultipleLocationsActorBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_AJBMultipleLocationsActorBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBMultipleLocationsActorBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBMultipleLocationsActorBase.BP_AJBMultipleLocationsActorBase_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_AJBMultipleLocationsActorBase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBMultipleLocationsActorBase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
