#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJB3DGuide

#include "Basic.hpp"

#include "BP_AJB3DGuide_classes.hpp"
#include "BP_AJB3DGuide_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AJB3DGuide.BP_AJB3DGuide_C.UpdateGuide
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FVector>&                 PathPositions                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void ABP_AJB3DGuide_C::UpdateGuide(TArray<struct FVector>& PathPositions)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJB3DGuide_C", "UpdateGuide");

	Params::BP_AJB3DGuide_C_UpdateGuide Parms{};

	Parms.PathPositions = std::move(PathPositions);

	UObject::ProcessEvent(Func, &Parms);

	PathPositions = std::move(Parms.PathPositions);
}


// Function BP_AJB3DGuide.BP_AJB3DGuide_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_AJB3DGuide_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJB3DGuide_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
