#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBGiveFzCondition

#include "Basic.hpp"

#include "BP_AJBGiveFzCondition_classes.hpp"
#include "BP_AJBGiveFzCondition_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.ExecuteUbergraph_BP_AJBGiveFzCondition
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBGiveFzCondition_C::ExecuteUbergraph_BP_AJBGiveFzCondition(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "ExecuteUbergraph_BP_AJBGiveFzCondition");

	Params::BP_AJBGiveFzCondition_C_ExecuteUbergraph_BP_AJBGiveFzCondition Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.SpawnEndEffect
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::SpawnEndEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "SpawnEndEffect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.InactiveAction
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::InactiveAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "InactiveAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.ChangeEnable
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enable                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_AJBGiveFzCondition_C::ChangeEnable(bool Enable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "ChangeEnable");

	Params::BP_AJBGiveFzCondition_C_ChangeEnable Parms{};

	Parms.Enable = Enable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.AddStatusGamePlayTag
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::AddStatusGamePlayTag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "AddStatusGamePlayTag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.RemoveStatusGamePlayTag
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::RemoveStatusGamePlayTag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "RemoveStatusGamePlayTag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.TryCreateDMIs
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::TryCreateDMIs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "TryCreateDMIs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.OnRep_CurrentFzConditionValue
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::OnRep_CurrentFzConditionValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "OnRep_CurrentFzConditionValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.SetPoliticMoveSpeed
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::SetPoliticMoveSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "SetPoliticMoveSpeed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.SetPoliticCameraSpeed
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::SetPoliticCameraSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "SetPoliticCameraSpeed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.SetPPOpacity
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBGiveFzCondition_C::SetPPOpacity(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "SetPPOpacity");

	Params::BP_AJBGiveFzCondition_C_SetPPOpacity Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.GetEndParticleTag
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FGameplayTag*                    EndParticleTag_0                                       (Parm, OutParm, NoDestructor, HasGetValueTypeHash)

void UBP_AJBGiveFzCondition_C::GetEndParticleTag(struct FGameplayTag* EndParticleTag_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "GetEndParticleTag");

	Params::BP_AJBGiveFzCondition_C_GetEndParticleTag Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (EndParticleTag_0 != nullptr)
		*EndParticleTag_0 = std::move(Parms.EndParticleTag_0);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.SetParticleFresnelOpacity
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBGiveFzCondition_C::SetParticleFresnelOpacity(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "SetParticleFresnelOpacity");

	Params::BP_AJBGiveFzCondition_C_SetParticleFresnelOpacity Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.CheckSpeedUpRate
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::CheckSpeedUpRate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "CheckSpeedUpRate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.SetMovementDistanceScale
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::SetMovementDistanceScale()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "SetMovementDistanceScale");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.OnContinuedParticleActivated
// (BlueprintCallable, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::OnContinuedParticleActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "OnContinuedParticleActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_AJBGiveFzCondition_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.OnActionInactivate
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bTriggeredByStand                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_AJBGiveFzCondition_C::OnActionInactivate(bool bTriggeredByStand)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "OnActionInactivate");

	Params::BP_AJBGiveFzCondition_C_OnActionInactivate Parms{};

	Parms.bTriggeredByStand = bTriggeredByStand;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.OnActionActivate
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bTriggeredByStand                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_AJBGiveFzCondition_C::OnActionActivate(bool bTriggeredByStand)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "OnActionActivate");

	Params::BP_AJBGiveFzCondition_C_OnActionActivate Parms{};

	Parms.bTriggeredByStand = bTriggeredByStand;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.UpdateLeftTime
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Causer                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBGiveFzCondition_C::UpdateLeftTime(class UObject* Causer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "UpdateLeftTime");

	Params::BP_AJBGiveFzCondition_C_UpdateLeftTime Parms{};

	Parms.Causer = Causer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.ActivePassive
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Causer                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bTriggeredByStand                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FGameplayTag&              CauserType                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// int32                                   SerialNumber                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          PropagationSource_0                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBGiveFzCondition_C::ActivePassive(class UObject* Causer, bool bTriggeredByStand, const struct FGameplayTag& CauserType, int32 SerialNumber, class UObject* PropagationSource_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "ActivePassive");

	Params::BP_AJBGiveFzCondition_C_ActivePassive Parms{};

	Parms.Causer = Causer;
	Parms.bTriggeredByStand = bTriggeredByStand;
	Parms.CauserType = std::move(CauserType);
	Parms.SerialNumber = SerialNumber;
	Parms.PropagationSource_0 = PropagationSource_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AJBGiveFzCondition_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "ReceiveTick");

	Params::BP_AJBGiveFzCondition_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.NotifyTheWorld
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AAJBInGameCharacter*              Operator                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EGeneralTiming                          Timing                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bEnable                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bOperatorIsEmpty                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_AJBGiveFzCondition_C::NotifyTheWorld(class AAJBInGameCharacter* Operator, float Time, EGeneralTiming Timing, bool bEnable, bool bOperatorIsEmpty)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "NotifyTheWorld");

	Params::BP_AJBGiveFzCondition_C_NotifyTheWorld Parms{};

	Parms.Operator = Operator;
	Parms.Time = Time;
	Parms.Timing = Timing;
	Parms.bEnable = bEnable;
	Parms.bOperatorIsEmpty = bOperatorIsEmpty;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.SkillAffecterAreaOut
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              SkillTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UBP_AJBGiveFzCondition_C::SkillAffecterAreaOut(const struct FGameplayTag& SkillTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "SkillAffecterAreaOut");

	Params::BP_AJBGiveFzCondition_C_SkillAffecterAreaOut Parms{};

	Parms.SkillTag = std::move(SkillTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBGiveFzCondition.BP_AJBGiveFzCondition_C.SkillAffecterAreaIn
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              SkillTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UBP_AJBGiveFzCondition_C::SkillAffecterAreaIn(const struct FGameplayTag& SkillTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBGiveFzCondition_C", "SkillAffecterAreaIn");

	Params::BP_AJBGiveFzCondition_C_SkillAffecterAreaIn Parms{};

	Parms.SkillTag = std::move(SkillTag);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
