#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBInGameProjectileTrailBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_AJBActorBase_classes.hpp"
#include "AJB_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AJBInGameProjectileTrailBase.BP_AJBInGameProjectileTrailBase_C
// 0x0018 (0x0348 - 0x0330)
class ABP_AJBInGameProjectileTrailBase_C : public ABP_AJBActorBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0330(0x0008)(Transient, DuplicateTransient)
	class UParticleSystemComponent*               TrailParticle_GL;                                  // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               TrailParticle;                                     // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_AJBInGameProjectileTrailBase(int32 EntryPoint);
	void OnOwnerDestroyed(class AActor* DestroyedActor);
	void ReceiveBeginPlay();
	void NotifyTheWorld(class AAJBInGameCharacter* Operator, float Time, EGeneralTiming Timing, bool bEnable, bool bOperatorIsEmpty);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AJBInGameProjectileTrailBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AJBInGameProjectileTrailBase_C")
	}
	static class ABP_AJBInGameProjectileTrailBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AJBInGameProjectileTrailBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_AJBInGameProjectileTrailBase_C;

SDK_NAMESPACE_END
