#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AJBVirusSmokeAffecter

#include "Basic.hpp"

#include "BP_AJBVirusSmokeAffecter_classes.hpp"
#include "BP_AJBVirusSmokeAffecter_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AJBVirusSmokeAffecter.BP_AJBVirusSmokeAffecter_C.ExecuteUbergraph_BP_AJBVirusSmokeAffecter
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBVirusSmokeAffecter_C::ExecuteUbergraph_BP_AJBVirusSmokeAffecter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBVirusSmokeAffecter_C", "ExecuteUbergraph_BP_AJBVirusSmokeAffecter");

	Params::BP_AJBVirusSmokeAffecter_C_ExecuteUbergraph_BP_AJBVirusSmokeAffecter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBVirusSmokeAffecter.BP_AJBVirusSmokeAffecter_C.GetCauserOwnerCharacterBP
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AJBInGameCharacter_C**        CharacterBP                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBVirusSmokeAffecter_C::GetCauserOwnerCharacterBP(class ABP_AJBInGameCharacter_C** CharacterBP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBVirusSmokeAffecter_C", "GetCauserOwnerCharacterBP");

	Params::BP_AJBVirusSmokeAffecter_C_GetCauserOwnerCharacterBP Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CharacterBP != nullptr)
		*CharacterBP = Parms.CharacterBP;
}


// Function BP_AJBVirusSmokeAffecter.BP_AJBVirusSmokeAffecter_C.GetPassiveSkillTag
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag*                    PassiveSkillTag_0                                      (Parm, OutParm, NoDestructor, HasGetValueTypeHash)

void ABP_AJBVirusSmokeAffecter_C::GetPassiveSkillTag(struct FGameplayTag* PassiveSkillTag_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBVirusSmokeAffecter_C", "GetPassiveSkillTag");

	Params::BP_AJBVirusSmokeAffecter_C_GetPassiveSkillTag Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PassiveSkillTag_0 != nullptr)
		*PassiveSkillTag_0 = std::move(Parms.PassiveSkillTag_0);
}


// Function BP_AJBVirusSmokeAffecter.BP_AJBVirusSmokeAffecter_C.GetDuration
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float*                                  Duration                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBVirusSmokeAffecter_C::GetDuration(float* Duration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBVirusSmokeAffecter_C", "GetDuration");

	Params::BP_AJBVirusSmokeAffecter_C_GetDuration Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Duration != nullptr)
		*Duration = Parms.Duration;
}


// Function BP_AJBVirusSmokeAffecter.BP_AJBVirusSmokeAffecter_C.OnAddPassiveFirst
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bAddSelf                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AAJBInGameCharacterBase*          TargetCharacter                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBVirusSmokeAffecter_C::OnAddPassiveFirst(bool bAddSelf, class AAJBInGameCharacterBase* TargetCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBVirusSmokeAffecter_C", "OnAddPassiveFirst");

	Params::BP_AJBVirusSmokeAffecter_C_OnAddPassiveFirst Parms{};

	Parms.bAddSelf = bAddSelf;
	Parms.TargetCharacter = TargetCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AJBVirusSmokeAffecter.BP_AJBVirusSmokeAffecter_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_AJBVirusSmokeAffecter_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBVirusSmokeAffecter_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AJBVirusSmokeAffecter.BP_AJBVirusSmokeAffecter_C.CalcScale
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  Scale_0                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AJBVirusSmokeAffecter_C::CalcScale(int32 Index_0, float* Scale_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AJBVirusSmokeAffecter_C", "CalcScale");

	Params::BP_AJBVirusSmokeAffecter_C_CalcScale Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Scale_0 != nullptr)
		*Scale_0 = Parms.Scale_0;
}


SDK_NAMESPACE_END
