#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPF_AJBInGameDebugFunctionLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPF_AJBInGameDebugFunctionLibrary.BPF_AJBInGameDebugFunctionLibrary_C
// 0x0000 (0x0028 - 0x0028)
class UBPF_AJBInGameDebugFunctionLibrary_C final : public UBlueprintFunctionLibrary
{
public:
	static class FString DebugGetControllerObjectNameFromActor(class AActor* Actor, const class FString& StringIfNotHasController, class UObject* __WorldContext);
	static void DebugGetPairObjectsNameFromActor(class AActor* Actor, const class FString& StringIfNotHasPair, class UObject* __WorldContext, class FString* PairCharacterObjectName, class FString* PairControllerObjectName);
	static class FString DebugShortenCharacterObjectName(const class FString& ObjectName, class UObject* __WorldContext);
	static class FString DebugShortenControllerObjectName(const class FString& ObjectName, class UObject* __WorldContext);
	static TMap<class FName, struct FGameplayTag> DebugGetAvailableCharacterTags(bool bAvailableNegotiationsCharacter, bool bSelectable, bool bUsableAsNPC, bool bShipping, class UObject* __WorldContext);
	static void DrawCross(const struct FVector2D& Location, class UObject* __WorldContext);
	static void ClearAllCrosses(class UObject* __WorldContext);
	static void DrawOutlineRect(const struct FBox2D& Box, class UObject* __WorldContext);
	static void ClearAllOutlineRects(class UObject* __WorldContext);
	static void DrawDebugText(const class FString& Text, const struct FVector2D& Location, class UObject* __WorldContext);
	static void ClearAllDebugTexts(class UObject* __WorldContext);
	static void DrawCrossWithColor(const struct FVector2D& Location, const struct FLinearColor& Color, class UObject* __WorldContext);
	static void DrawDebugGrid(const struct FVector& CenterLocation, const struct FRotator& PlaneRotation, const struct FVector2D& Size, const struct FLinearColor& LineColor, float LifeTime, float Thickness, const struct FIntPoint& GridNum, class UObject* __WorldContext);
	static void DrawBoxGauge(const struct FBox2D& Box, float GaugeMax, float GaugeValue, class UObject* __WorldContext);
	static void DrawBoxGaugeWithColor(const struct FBox2D& Box, float GaugeMax, float GaugeValue, const struct FLinearColor& OutlineColor, const struct FLinearColor& FilledColor, class UObject* __WorldContext);

	static void GetDebugScreenDrawHelper(class UObject* __WorldContext, bool* Success, class UBP_AJBDebugScreenDrawHelper_C** DebugScreenDrawHelper);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPF_AJBInGameDebugFunctionLibrary_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPF_AJBInGameDebugFunctionLibrary_C")
	}
	static class UBPF_AJBInGameDebugFunctionLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPF_AJBInGameDebugFunctionLibrary_C>();
	}
};
DUMPER7_ASSERTS_UBPF_AJBInGameDebugFunctionLibrary_C;

SDK_NAMESPACE_END
