#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_BattleRecord

#include "Basic.hpp"

#include "WB_BattleRecord_classes.hpp"
#include "WB_BattleRecord_parameters.hpp"


SDK_NAMESPACE_START

// Function WB_BattleRecord.WB_BattleRecord_C.ExecuteUbergraph_WB_BattleRecord
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_BattleRecord_C::ExecuteUbergraph_WB_BattleRecord(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "ExecuteUbergraph_WB_BattleRecord");

	Params::WB_BattleRecord_C_ExecuteUbergraph_WB_BattleRecord Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_BattleRecord.WB_BattleRecord_C.BndEvt__Appear_VeryGood_K2Node_ComponentBoundEvent_6_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UWB_BattleRecord_C::BndEvt__Appear_VeryGood_K2Node_ComponentBoundEvent_6_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "BndEvt__Appear_VeryGood_K2Node_ComponentBoundEvent_6_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.BndEvt__Appear_Good_K2Node_ComponentBoundEvent_5_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UWB_BattleRecord_C::BndEvt__Appear_Good_K2Node_ComponentBoundEvent_5_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "BndEvt__Appear_Good_K2Node_ComponentBoundEvent_5_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.BndEvt__Detail_Good_Damage_K2Node_ComponentBoundEvent_4_OnEndAnimDispatcher__DelegateSignature
// (BlueprintEvent)

void UWB_BattleRecord_C::BndEvt__Detail_Good_Damage_K2Node_ComponentBoundEvent_4_OnEndAnimDispatcher__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "BndEvt__Detail_Good_Damage_K2Node_ComponentBoundEvent_4_OnEndAnimDispatcher__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.BndEvt__Detail_Good_Skill_K2Node_ComponentBoundEvent_3_OnEndAnimDispatcher__DelegateSignature
// (BlueprintEvent)

void UWB_BattleRecord_C::BndEvt__Detail_Good_Skill_K2Node_ComponentBoundEvent_3_OnEndAnimDispatcher__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "BndEvt__Detail_Good_Skill_K2Node_ComponentBoundEvent_3_OnEndAnimDispatcher__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.BndEvt__Detail_Good_Kill_K2Node_ComponentBoundEvent_2_OnEndAnimDispatcher__DelegateSignature
// (BlueprintEvent)

void UWB_BattleRecord_C::BndEvt__Detail_Good_Kill_K2Node_ComponentBoundEvent_2_OnEndAnimDispatcher__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "BndEvt__Detail_Good_Kill_K2Node_ComponentBoundEvent_2_OnEndAnimDispatcher__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.BndEvt__Detail_Good_LivingTime_K2Node_ComponentBoundEvent_1_OnEndAnimDispatcher__DelegateSignature
// (BlueprintEvent)

void UWB_BattleRecord_C::BndEvt__Detail_Good_LivingTime_K2Node_ComponentBoundEvent_1_OnEndAnimDispatcher__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "BndEvt__Detail_Good_LivingTime_K2Node_ComponentBoundEvent_1_OnEndAnimDispatcher__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnDeterminRank
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   BattleGameRank                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   BattleGameRankWithoutCPU                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_BattleRecord_C::OnDeterminRank(int32 BattleGameRank, int32 BattleGameRankWithoutCPU)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnDeterminRank");

	Params::WB_BattleRecord_C_OnDeterminRank Parms{};

	Parms.BattleGameRank = BattleGameRank;
	Parms.BattleGameRankWithoutCPU = BattleGameRankWithoutCPU;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_BattleRecord.WB_BattleRecord_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_BattleRecord_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.ForceClosePairAlertConfirm
// (BlueprintCallable, BlueprintEvent)

void UWB_BattleRecord_C::ForceClosePairAlertConfirm()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "ForceClosePairAlertConfirm");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnFinishedConfirm
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EAJBConfirmResult                       Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_BattleRecord_C::OnFinishedConfirm(EAJBConfirmResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnFinishedConfirm");

	Params::WB_BattleRecord_C_OnFinishedConfirm Parms{};

	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_BattleRecord.WB_BattleRecord_C.ShowAlertPairConfirm
// (BlueprintCallable, BlueprintEvent)

void UWB_BattleRecord_C::ShowAlertPairConfirm()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "ShowAlertPairConfirm");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_BattleRecord_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "Tick");

	Params::WB_BattleRecord_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_BattleRecord.WB_BattleRecord_C.GotoOutGame
// (BlueprintCallable, BlueprintEvent)

void UWB_BattleRecord_C::GotoOutGame()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "GotoOutGame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.GotoPlayerWatching
// (BlueprintCallable, BlueprintEvent)

void UWB_BattleRecord_C::GotoPlayerWatching()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "GotoPlayerWatching");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnAutoTransitionsPlayerWatching
// (BlueprintCallable, BlueprintEvent)

void UWB_BattleRecord_C::OnAutoTransitionsPlayerWatching()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnAutoTransitionsPlayerWatching");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnFinishedAnim
// (BlueprintCallable, BlueprintEvent)

void UWB_BattleRecord_C::OnFinishedAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnFinishedAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnClosingWindow
// (Event, Public, BlueprintEvent)

void UWB_BattleRecord_C::OnClosingWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnClosingWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnOpeningWindow
// (Event, Public, BlueprintEvent)

void UWB_BattleRecord_C::OnOpeningWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnOpeningWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.BndEvt__GameEndButton_K2Node_ComponentBoundEvent_55_OnAJBButtonEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAJBButtonWidget*                 OwnerWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAJBButton*                       TargetButton                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_BattleRecord_C::BndEvt__GameEndButton_K2Node_ComponentBoundEvent_55_OnAJBButtonEvent__DelegateSignature(class UAJBButtonWidget* OwnerWidget, class UAJBButton* TargetButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "BndEvt__GameEndButton_K2Node_ComponentBoundEvent_55_OnAJBButtonEvent__DelegateSignature");

	Params::WB_BattleRecord_C_BndEvt__GameEndButton_K2Node_ComponentBoundEvent_55_OnAJBButtonEvent__DelegateSignature Parms{};

	Parms.OwnerWidget = OwnerWidget;
	Parms.TargetButton = TargetButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_BattleRecord.WB_BattleRecord_C.BndEvt__RetireButton_K2Node_ComponentBoundEvent_46_OnAJBButtonEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAJBButtonWidget*                 OwnerWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAJBButton*                       TargetButton                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_BattleRecord_C::BndEvt__RetireButton_K2Node_ComponentBoundEvent_46_OnAJBButtonEvent__DelegateSignature(class UAJBButtonWidget* OwnerWidget, class UAJBButton* TargetButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "BndEvt__RetireButton_K2Node_ComponentBoundEvent_46_OnAJBButtonEvent__DelegateSignature");

	Params::WB_BattleRecord_C_BndEvt__RetireButton_K2Node_ComponentBoundEvent_46_OnAJBButtonEvent__DelegateSignature Parms{};

	Parms.OwnerWidget = OwnerWidget;
	Parms.TargetButton = TargetButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_BattleRecord.WB_BattleRecord_C.CanPlayerWatching
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   bCan                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_BattleRecord_C::CanPlayerWatching(bool* bCan)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "CanPlayerWatching");

	Params::WB_BattleRecord_C_CanPlayerWatching Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bCan != nullptr)
		*bCan = Parms.bCan;
}


// Function WB_BattleRecord.WB_BattleRecord_C.IsAlivePiarCharacter
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   bActive                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_BattleRecord_C::IsAlivePiarCharacter(bool* bActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "IsAlivePiarCharacter");

	Params::WB_BattleRecord_C_IsAlivePiarCharacter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bActive != nullptr)
		*bActive = Parms.bActive;
}


// Function WB_BattleRecord.WB_BattleRecord_C.ChangeGameEndButtonDisplay
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWB_BattleRecord_C::ChangeGameEndButtonDisplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "ChangeGameEndButtonDisplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.ChangeWatchingPlayerButtonDisplay
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWB_BattleRecord_C::ChangeWatchingPlayerButtonDisplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "ChangeWatchingPlayerButtonDisplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedUp
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedUp");

	Params::WB_BattleRecord_C_OnInputReleasedUp Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedRight
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedRight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedRight");

	Params::WB_BattleRecord_C_OnInputReleasedRight Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedLeft
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedLeft()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedLeft");

	Params::WB_BattleRecord_C_OnInputReleasedLeft Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedDown
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedDown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedDown");

	Params::WB_BattleRecord_C_OnInputReleasedDown Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedDecide
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedDecide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedDecide");

	Params::WB_BattleRecord_C_OnInputReleasedDecide Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedCancel
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedCancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedCancel");

	Params::WB_BattleRecord_C_OnInputReleasedCancel Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedUp
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedUp");

	Params::WB_BattleRecord_C_OnInputPressedUp Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedRight
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedRight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedRight");

	Params::WB_BattleRecord_C_OnInputPressedRight Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedLeft
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedLeft()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedLeft");

	Params::WB_BattleRecord_C_OnInputPressedLeft Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedDown
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedDown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedDown");

	Params::WB_BattleRecord_C_OnInputPressedDown Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedDecide
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedDecide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedDecide");

	Params::WB_BattleRecord_C_OnInputPressedDecide Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedCancel
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedCancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedCancel");

	Params::WB_BattleRecord_C_OnInputPressedCancel Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.IsModeless
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::IsModeless()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "IsModeless");

	Params::WB_BattleRecord_C_IsModeless Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputTurnRate
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputTurnRate(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputTurnRate");

	Params::WB_BattleRecord_C_OnInputTurnRate Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputMoveRight
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputMoveRight(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputMoveRight");

	Params::WB_BattleRecord_C_OnInputMoveRight Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputMoveForward
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputMoveForward(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputMoveForward");

	Params::WB_BattleRecord_C_OnInputMoveForward Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputLookupRate
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputLookupRate(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputLookupRate");

	Params::WB_BattleRecord_C_OnInputLookupRate Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedTouch
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedTouch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedTouch");

	Params::WB_BattleRecord_C_OnInputReleasedTouch Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedTouch
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const float                             LocationX                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const float                             LocationY                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedTouch(const float LocationX, const float LocationY)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedTouch");

	Params::WB_BattleRecord_C_OnInputPressedTouch Parms{};

	Parms.LocationX = LocationX;
	Parms.LocationY = LocationY;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedR2
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedR2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedR2");

	Params::WB_BattleRecord_C_OnInputReleasedR2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedR1
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedR1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedR1");

	Params::WB_BattleRecord_C_OnInputReleasedR1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedL2
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedL2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedL2");

	Params::WB_BattleRecord_C_OnInputReleasedL2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedL1
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedL1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedL1");

	Params::WB_BattleRecord_C_OnInputReleasedL1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedR2
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedR2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedR2");

	Params::WB_BattleRecord_C_OnInputPressedR2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedR1
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedR1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedR1");

	Params::WB_BattleRecord_C_OnInputPressedR1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedL2
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedL2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedL2");

	Params::WB_BattleRecord_C_OnInputPressedL2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedL1
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedL1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedL1");

	Params::WB_BattleRecord_C_OnInputPressedL1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputReleasedL3
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputReleasedL3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputReleasedL3");

	Params::WB_BattleRecord_C_OnInputReleasedL3 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedL3
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedL3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedL3");

	Params::WB_BattleRecord_C_OnInputPressedL3 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedY
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedY()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedY");

	Params::WB_BattleRecord_C_OnInputPressedY Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_BattleRecord.WB_BattleRecord_C.OnInputPressedX
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_BattleRecord_C::OnInputPressedX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_BattleRecord_C", "OnInputPressedX");

	Params::WB_BattleRecord_C_OnInputPressedX Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
