#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_StandBy_Setting

#include "Basic.hpp"

#include "WB_StandBy_Setting_classes.hpp"
#include "WB_StandBy_Setting_parameters.hpp"


SDK_NAMESPACE_START

// Function WB_StandBy_Setting.WB_StandBy_Setting_C.ExecuteUbergraph_WB_StandBy_Setting
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_StandBy_Setting_C::ExecuteUbergraph_WB_StandBy_Setting(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "ExecuteUbergraph_WB_StandBy_Setting");

	Params::WB_StandBy_Setting_C_ExecuteUbergraph_WB_StandBy_Setting Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.OnOpeningWindow
// (Event, Public, BlueprintEvent)

void UWB_StandBy_Setting_C::OnOpeningWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "OnOpeningWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.OnClosingWindow
// (Event, Public, BlueprintEvent)

void UWB_StandBy_Setting_C::OnClosingWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "OnClosingWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_StandBy_Setting_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.BndEvt__WB_CommonButton_OK_K2Node_ComponentBoundEvent_7_OnAJBButtonEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAJBButtonWidget*                 OwnerWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAJBButton*                       TargetButton                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_StandBy_Setting_C::BndEvt__WB_CommonButton_OK_K2Node_ComponentBoundEvent_7_OnAJBButtonEvent__DelegateSignature(class UAJBButtonWidget* OwnerWidget, class UAJBButton* TargetButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "BndEvt__WB_CommonButton_OK_K2Node_ComponentBoundEvent_7_OnAJBButtonEvent__DelegateSignature");

	Params::WB_StandBy_Setting_C_BndEvt__WB_CommonButton_OK_K2Node_ComponentBoundEvent_7_OnAJBButtonEvent__DelegateSignature Parms{};

	Parms.OwnerWidget = OwnerWidget;
	Parms.TargetButton = TargetButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.BndEvt__WB_CommonButton_CANCEL_K2Node_ComponentBoundEvent_6_OnAJBButtonEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAJBButtonWidget*                 OwnerWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAJBButton*                       TargetButton                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_StandBy_Setting_C::BndEvt__WB_CommonButton_CANCEL_K2Node_ComponentBoundEvent_6_OnAJBButtonEvent__DelegateSignature(class UAJBButtonWidget* OwnerWidget, class UAJBButton* TargetButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "BndEvt__WB_CommonButton_CANCEL_K2Node_ComponentBoundEvent_6_OnAJBButtonEvent__DelegateSignature");

	Params::WB_StandBy_Setting_C_BndEvt__WB_CommonButton_CANCEL_K2Node_ComponentBoundEvent_6_OnAJBButtonEvent__DelegateSignature Parms{};

	Parms.OwnerWidget = OwnerWidget;
	Parms.TargetButton = TargetButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.BndEvt__WB_ArrowButton_CPUStrengthUp_K2Node_ComponentBoundEvent_5_OnAJBButtonEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAJBButtonWidget*                 OwnerWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAJBButton*                       TargetButton                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_StandBy_Setting_C::BndEvt__WB_ArrowButton_CPUStrengthUp_K2Node_ComponentBoundEvent_5_OnAJBButtonEvent__DelegateSignature(class UAJBButtonWidget* OwnerWidget, class UAJBButton* TargetButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "BndEvt__WB_ArrowButton_CPUStrengthUp_K2Node_ComponentBoundEvent_5_OnAJBButtonEvent__DelegateSignature");

	Params::WB_StandBy_Setting_C_BndEvt__WB_ArrowButton_CPUStrengthUp_K2Node_ComponentBoundEvent_5_OnAJBButtonEvent__DelegateSignature Parms{};

	Parms.OwnerWidget = OwnerWidget;
	Parms.TargetButton = TargetButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.BndEvt__WB_ArrowButton_CPUStrengthDown_K2Node_ComponentBoundEvent_4_OnAJBButtonEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAJBButtonWidget*                 OwnerWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAJBButton*                       TargetButton                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_StandBy_Setting_C::BndEvt__WB_ArrowButton_CPUStrengthDown_K2Node_ComponentBoundEvent_4_OnAJBButtonEvent__DelegateSignature(class UAJBButtonWidget* OwnerWidget, class UAJBButton* TargetButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "BndEvt__WB_ArrowButton_CPUStrengthDown_K2Node_ComponentBoundEvent_4_OnAJBButtonEvent__DelegateSignature");

	Params::WB_StandBy_Setting_C_BndEvt__WB_ArrowButton_CPUStrengthDown_K2Node_ComponentBoundEvent_4_OnAJBButtonEvent__DelegateSignature Parms{};

	Parms.OwnerWidget = OwnerWidget;
	Parms.TargetButton = TargetButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.BndEvt__WB_ArrowButton_CPUNumUp_K2Node_ComponentBoundEvent_3_OnAJBButtonEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAJBButtonWidget*                 OwnerWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAJBButton*                       TargetButton                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_StandBy_Setting_C::BndEvt__WB_ArrowButton_CPUNumUp_K2Node_ComponentBoundEvent_3_OnAJBButtonEvent__DelegateSignature(class UAJBButtonWidget* OwnerWidget, class UAJBButton* TargetButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "BndEvt__WB_ArrowButton_CPUNumUp_K2Node_ComponentBoundEvent_3_OnAJBButtonEvent__DelegateSignature");

	Params::WB_StandBy_Setting_C_BndEvt__WB_ArrowButton_CPUNumUp_K2Node_ComponentBoundEvent_3_OnAJBButtonEvent__DelegateSignature Parms{};

	Parms.OwnerWidget = OwnerWidget;
	Parms.TargetButton = TargetButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.BndEvt__WB_ArrowButton_CPUNumDown_K2Node_ComponentBoundEvent_2_OnAJBButtonEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAJBButtonWidget*                 OwnerWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAJBButton*                       TargetButton                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_StandBy_Setting_C::BndEvt__WB_ArrowButton_CPUNumDown_K2Node_ComponentBoundEvent_2_OnAJBButtonEvent__DelegateSignature(class UAJBButtonWidget* OwnerWidget, class UAJBButton* TargetButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "BndEvt__WB_ArrowButton_CPUNumDown_K2Node_ComponentBoundEvent_2_OnAJBButtonEvent__DelegateSignature");

	Params::WB_StandBy_Setting_C_BndEvt__WB_ArrowButton_CPUNumDown_K2Node_ComponentBoundEvent_2_OnAJBButtonEvent__DelegateSignature Parms{};

	Parms.OwnerWidget = OwnerWidget;
	Parms.TargetButton = TargetButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.UpdateCPUStrength
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ETrainingCPUStrength                    CPUStrength                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_StandBy_Setting_C::UpdateCPUStrength(ETrainingCPUStrength CPUStrength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "UpdateCPUStrength");

	Params::WB_StandBy_Setting_C_UpdateCPUStrength Parms{};

	Parms.CPUStrength = CPUStrength;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.OnFinishedOpenCurveAnim
// (BlueprintCallable, BlueprintEvent)

void UWB_StandBy_Setting_C::OnFinishedOpenCurveAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "OnFinishedOpenCurveAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_StandBy_Setting.WB_StandBy_Setting_C.UpdateCPUNum
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Num                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_StandBy_Setting_C::UpdateCPUNum(int32 Num)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_StandBy_Setting_C", "UpdateCPUNum");

	Params::WB_StandBy_Setting_C_UpdateCPUNum Parms{};

	Parms.Num = Num;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
