#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_TestModeMenuItemInteger

#include "Basic.hpp"

#include "WB_TestModeMenuItemInteger_classes.hpp"
#include "WB_TestModeMenuItemInteger_parameters.hpp"


SDK_NAMESPACE_START

// Function WB_TestModeMenuItemInteger.WB_TestModeMenuItemInteger_C.ExecuteUbergraph_WB_TestModeMenuItemInteger
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_TestModeMenuItemInteger_C::ExecuteUbergraph_WB_TestModeMenuItemInteger(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TestModeMenuItemInteger_C", "ExecuteUbergraph_WB_TestModeMenuItemInteger");

	Params::WB_TestModeMenuItemInteger_C_ExecuteUbergraph_WB_TestModeMenuItemInteger Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_TestModeMenuItemInteger.WB_TestModeMenuItemInteger_C.SetSelectValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Value_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_TestModeMenuItemInteger_C::SetSelectValue(int32 Value_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TestModeMenuItemInteger_C", "SetSelectValue");

	Params::WB_TestModeMenuItemInteger_C_SetSelectValue Parms{};

	Parms.Value_0 = Value_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_TestModeMenuItemInteger.WB_TestModeMenuItemInteger_C.ModifyMinValue
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_TestModeMenuItemInteger_C::ModifyMinValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TestModeMenuItemInteger_C", "ModifyMinValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TestModeMenuItemInteger.WB_TestModeMenuItemInteger_C.ModifyMaxValue
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_TestModeMenuItemInteger_C::ModifyMaxValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TestModeMenuItemInteger_C", "ModifyMaxValue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TestModeMenuItemInteger.WB_TestModeMenuItemInteger_C.ValueDown
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_TestModeMenuItemInteger_C::ValueDown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TestModeMenuItemInteger_C", "ValueDown");

	Params::WB_TestModeMenuItemInteger_C_ValueDown Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_TestModeMenuItemInteger.WB_TestModeMenuItemInteger_C.ValueUp
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsMax                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_TestModeMenuItemInteger_C::ValueUp(bool* IsMax)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TestModeMenuItemInteger_C", "ValueUp");

	Params::WB_TestModeMenuItemInteger_C_ValueUp Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsMax != nullptr)
		*IsMax = Parms.IsMax;
}


// Function WB_TestModeMenuItemInteger.WB_TestModeMenuItemInteger_C.IsDefaultValue
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_TestModeMenuItemInteger_C::IsDefaultValue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TestModeMenuItemInteger_C", "IsDefaultValue");

	Params::WB_TestModeMenuItemInteger_C_IsDefaultValue Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_TestModeMenuItemInteger.WB_TestModeMenuItemInteger_C.GetValueText
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText*                            OutText                                                (Parm, OutParm)

void UWB_TestModeMenuItemInteger_C::GetValueText(class FText* OutText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TestModeMenuItemInteger_C", "GetValueText");

	Params::WB_TestModeMenuItemInteger_C_GetValueText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutText != nullptr)
		*OutText = std::move(Parms.OutText);
}


SDK_NAMESPACE_END
