#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_UI_PairDownEffect

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WB_UI_PairDownEffect.WB_UI_PairDownEffect_C.ExecuteUbergraph_WB_UI_PairDownEffect
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x08) WB_UI_PairDownEffect_C_ExecuteUbergraph_WB_UI_PairDownEffect final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_GetAnimationCurrentTime_ReturnValue;      // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_UI_PairDownEffect_C_ExecuteUbergraph_WB_UI_PairDownEffect;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
