#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_UI_FollowPairInfo

#include "Basic.hpp"

#include "WB_UI_FollowPairInfo_classes.hpp"
#include "WB_UI_FollowPairInfo_parameters.hpp"


SDK_NAMESPACE_START

// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.ExecuteUbergraph_WB_UI_FollowPairInfo
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_UI_FollowPairInfo_C::ExecuteUbergraph_WB_UI_FollowPairInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "ExecuteUbergraph_WB_UI_FollowPairInfo");

	Params::WB_UI_FollowPairInfo_C_ExecuteUbergraph_WB_UI_FollowPairInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.UpdateClairvoyance
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bEnable                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_UI_FollowPairInfo_C::UpdateClairvoyance(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "UpdateClairvoyance");

	Params::WB_UI_FollowPairInfo_C_UpdateClairvoyance Parms{};

	Parms.bEnable = bEnable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.Update
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FTransform&                FollowTargetTransform                                  (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)

void UWB_UI_FollowPairInfo_C::Update(const struct FTransform& FollowTargetTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "Update");

	Params::WB_UI_FollowPairInfo_C_Update Parms{};

	Parms.FollowTargetTransform = std::move(FollowTargetTransform);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.Open
// (BlueprintCallable, BlueprintEvent)

void UWB_UI_FollowPairInfo_C::Open()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "Open");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.Close
// (BlueprintCallable, BlueprintEvent)

void UWB_UI_FollowPairInfo_C::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "Close");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.ShowPlayerNameOnly
// (BlueprintCallable, BlueprintEvent)

void UWB_UI_FollowPairInfo_C::ShowPlayerNameOnly()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "ShowPlayerNameOnly");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_UI_FollowPairInfo_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.SetPairHPAndAPAndCPAndSP
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   HpValue                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ApValue                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CPValue                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   MaxHpValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   MaxApValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   MaxCPValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SpValue                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_UI_FollowPairInfo_C::SetPairHPAndAPAndCPAndSP(float HpValue, float ApValue, float CPValue, float MaxHpValue, float MaxApValue, float MaxCPValue, int32 SpValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "SetPairHPAndAPAndCPAndSP");

	Params::WB_UI_FollowPairInfo_C_SetPairHPAndAPAndCPAndSP Parms{};

	Parms.HpValue = HpValue;
	Parms.ApValue = ApValue;
	Parms.CPValue = CPValue;
	Parms.MaxHpValue = MaxHpValue;
	Parms.MaxApValue = MaxApValue;
	Parms.MaxCPValue = MaxCPValue;
	Parms.SpValue = SpValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.SetupShopCompetitionPairInfo
// (BlueprintCallable, BlueprintEvent)

void UWB_UI_FollowPairInfo_C::SetupShopCompetitionPairInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "SetupShopCompetitionPairInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.SetEnabledInvisibleDistance
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInvisible                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_UI_FollowPairInfo_C::SetEnabledInvisibleDistance(bool bInvisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "SetEnabledInvisibleDistance");

	Params::WB_UI_FollowPairInfo_C_SetEnabledInvisibleDistance Parms{};

	Parms.bInvisible = bInvisible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.SetPairName
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWB_UI_FollowPairInfo_C::SetPairName(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "SetPairName");

	Params::WB_UI_FollowPairInfo_C_SetPairName Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.UpdateWidgetScale
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   NewScale                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   MaxMinScale                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   OffsetLocation                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_UI_FollowPairInfo_C::UpdateWidgetScale(float NewScale, float MaxMinScale, float OffsetLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "UpdateWidgetScale");

	Params::WB_UI_FollowPairInfo_C_UpdateWidgetScale Parms{};

	Parms.NewScale = NewScale;
	Parms.MaxMinScale = MaxMinScale;
	Parms.OffsetLocation = OffsetLocation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.UpdateDyingBar
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   BarValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_UI_FollowPairInfo_C::UpdateDyingBar(float BarValue, float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "UpdateDyingBar");

	Params::WB_UI_FollowPairInfo_C_UpdateDyingBar Parms{};

	Parms.BarValue = BarValue;
	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_UI_FollowPairInfo_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "Tick");

	Params::WB_UI_FollowPairInfo_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.UpdateArrowVisibility
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsOutViewPosition                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FVector2D&                 ScreenPosition                                         (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_UI_FollowPairInfo_C::UpdateArrowVisibility(bool bIsOutViewPosition, const struct FVector2D& ScreenPosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "UpdateArrowVisibility");

	Params::WB_UI_FollowPairInfo_C_UpdateArrowVisibility Parms{};

	Parms.bIsOutViewPosition = bIsOutViewPosition;
	Parms.ScreenPosition = std::move(ScreenPosition);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.GetHalfViewportSize
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_UI_FollowPairInfo_C::GetHalfViewportSize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "GetHalfViewportSize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.UpdatePairComponentPosition
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   PairWorldPosition                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_UI_FollowPairInfo_C::UpdatePairComponentPosition(const struct FVector& PairWorldPosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "UpdatePairComponentPosition");

	Params::WB_UI_FollowPairInfo_C_UpdatePairComponentPosition Parms{};

	Parms.PairWorldPosition = std::move(PairWorldPosition);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.ClampScreenPosition
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector2D&                       Position                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector2D*                       NewPosition                                            (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_UI_FollowPairInfo_C::ClampScreenPosition(struct FVector2D& Position, struct FVector2D* NewPosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "ClampScreenPosition");

	Params::WB_UI_FollowPairInfo_C_ClampScreenPosition Parms{};

	Parms.Position = std::move(Position);

	UObject::ProcessEvent(Func, &Parms);

	Position = std::move(Parms.Position);

	if (NewPosition != nullptr)
		*NewPosition = std::move(Parms.NewPosition);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.SetScreenPosHeaderHeightLimit
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Height                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_UI_FollowPairInfo_C::SetScreenPosHeaderHeightLimit(float Height)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "SetScreenPosHeaderHeightLimit");

	Params::WB_UI_FollowPairInfo_C_SetScreenPosHeaderHeightLimit Parms{};

	Parms.Height = Height;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.GetOrthant
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const struct FVector2D&                 ScreenPosition                                         (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Orthant                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_UI_FollowPairInfo_C::GetOrthant(const struct FVector2D& ScreenPosition, int32* Orthant) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "GetOrthant");

	Params::WB_UI_FollowPairInfo_C_GetOrthant Parms{};

	Parms.ScreenPosition = std::move(ScreenPosition);

	UObject::ProcessEvent(Func, &Parms);

	if (Orthant != nullptr)
		*Orthant = Parms.Orthant;
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.GetDPIScaledDesiredSize
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FVector2D                        ReturnValue                                            (Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector2D UWB_UI_FollowPairInfo_C::GetDPIScaledDesiredSize() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "GetDPIScaledDesiredSize");

	Params::WB_UI_FollowPairInfo_C_GetDPIScaledDesiredSize Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_UI_FollowPairInfo.WB_UI_FollowPairInfo_C.IsInViewPositionFun
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const struct FVector2D&                 ScreenPosition                                         (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_UI_FollowPairInfo_C::IsInViewPositionFun(const struct FVector2D& ScreenPosition) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_UI_FollowPairInfo_C", "IsInViewPositionFun");

	Params::WB_UI_FollowPairInfo_C_IsInViewPositionFun Parms{};

	Parms.ScreenPosition = std::move(ScreenPosition);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
